export const initialManagedUsersData = [
  { id: 'user-1', index: 1, name: '김동인', roleLevel: '대표', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-9772-5939', email: 'shehdshehd1123@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-2', index: 2, name: '길가영', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-6595-3930', email: 'gilgayeong2@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-3', index: 3, name: '최진영', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-4558-3205', email: 'lucy3205@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-4', index: 4, name: '정재웅', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-7166-2296', email: 'greadex2296@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-5', index: 5, name: '박형규', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-5660-2425', email: '0518phg@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-6', index: 6, name: '배유진', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-5291-6172', email: 'yoojin.bae23@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-7', index: 7, name: '김빈섭', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-9923-4322', email: 'doo4322@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-8', index: 8, name: '이수민', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-2933-2815', email: 'leesuminn23@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-9', index: 9, name: '허승혁', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-9643-4117', email: 'heoseunghyeok0@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-10', index: 10, name: '천도현', roleLevel: '일반', department: '전자공학과', labProfessor: '김민회 교수님', phone: '010-5588-2490', email: 'cheondohyun99@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-11', index: 11, name: '김세형', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-8357-8849', email: 'kimsehyung1009@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-12', index: 12, name: '이현준', roleLevel: '일반', department: '창의융합학과', labProfessor: '김민회 교수님', phone: '010-4266-5253', email: 'hyeonjunlee917@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-13', index: 13, name: '김택균', roleLevel: '대표', department: '기계공학과', labProfessor: '노진성 교수님', phone: '010-4066-1760', email: 'kimtk1346@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-14', index: 14, name: '이동규', roleLevel: '일반', department: '기계공학과', labProfessor: '노진성 교수님', phone: '010-4878-3369', email: 'bestcubist@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-15', index: 15, name: '박준우', roleLevel: '일반', department: '기계공학과', labProfessor: '노진성 교수님', phone: '010-7487-5220', email: 'pjw981121@gmail.com', memo: '1학기 회의 참석 어려움(매주 화요일 19~22시 야간대 수업)', authProvider: 'Manual' },
  { id: 'user-16', index: 16, name: '강정민', roleLevel: '일반', department: '기계공학과', labProfessor: '노진성 교수님', phone: '010-5024-7735', email: 'Scipio.kang@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-17', index: 17, name: 'Chu Duc Thanh', roleLevel: '일반', department: '기계공학과', labProfessor: '노진성 교수님', phone: '010-5801-2310', email: 'chuducthanh972310@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-18', index: 18, name: 'Ngoc Tram Pham Le', roleLevel: '일반', department: '기계공학과', labProfessor: '노진성 교수님', phone: '010-7989-7771', email: 'ngoctram9128@outlook.com', memo: '', authProvider: 'Manual' },
  { id: 'user-19', index: 19, name: 'Truong Dang Thanh', roleLevel: '일반', department: '기계공학과', labProfessor: '노진성 교수님', phone: '010-8837-3979', email: 'michaeldangvn@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-20', index: 20, name: 'To Thi Tu Linh', roleLevel: '일반', department: '기계공학과', labProfessor: '노진성 교수님', phone: '010-3336-7762', email: 'tothitulinhche98@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-21', index: 21, name: '김서현', roleLevel: '대표', department: '창의융합학과', labProfessor: '이재현 교수님', phone: '010-6286-9373', email: 'kshg0419@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-22', index: 22, name: '이승진', roleLevel: '대표', department: '전자공학과', labProfessor: '전승배 교수님', phone: '010-4036-9815', email: '20201706@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-23', index: 23, name: '정우성', roleLevel: '일반', department: '지능형나노반도체학과', labProfessor: '전승배 교수님', phone: '010-2343-8349', email: 'dntjd1972@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-24', index: 24, name: '윤진언', roleLevel: '일반', department: '전자공학과', labProfessor: '전승배 교수님', phone: '010-2559-4804', email: '20211074@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-25', index: 25, name: '노우용', roleLevel: '일반', department: '전자공학과', labProfessor: '전승배 교수님', phone: '010-7550-5669', email: '20221167@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-26', index: 26, name: '박준성', roleLevel: '일반', department: '전자공학과', labProfessor: '전승배 교수님', phone: '010-5635-5915', email: 'qn0esnuj@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-27', index: 27, name: '정재영', roleLevel: '일반', department: '화학생명공학과', labProfessor: '전승배 교수님', phone: '010-2251-5596', email: 'jaeyoung0921@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-28', index: 28, name: '김재윤', roleLevel: '일반', department: '전자공학과', labProfessor: '전승배 교수님', phone: '010-9149-8203', email: 'jaeyun12245@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-29', index: 29, name: '한의정', roleLevel: '일반', department: '전자공학과', labProfessor: '전승배 교수님', phone: '010-5611-5441', email: 'eui_jeong@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-30', index: 30, name: '권준형', roleLevel: '대표', department: '지능형나노반도체학과', labProfessor: '최윤석 교수님', phone: '010-7590-0288', email: 'tmzkdlxka@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-31', index: 31, name: '성유진', roleLevel: '일반', department: '지능형나노반도체학과', labProfessor: '최윤석 교수님', phone: '010-9950-7504', email: 'dbwls010211@naver.com', memo: '5월 이후 회사 출근 (회의 및 청소 참여 어려움)', authProvider: 'Manual' },
  { id: 'user-32', index: 32, name: '권아현', roleLevel: '일반', department: '지능형나노반도체학과', labProfessor: '최윤석 교수님', phone: '010-5426-0458', email: 'kah0458@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-33', index: 33, name: '김보혜', roleLevel: '일반', department: '지능형나노반도체학과', labProfessor: '최윤석 교수님', phone: '010-7166-6290', email: 'qhgP6290@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-34', index: 34, name: '안현식', roleLevel: '일반', department: '전자공학과', labProfessor: '최윤석 교수님', phone: '010-9436-9445', email: 'princass123@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-35', index: 35, name: '임성민', roleLevel: '일반', department: '전자공학과', labProfessor: '최윤석 교수님', phone: '010-4870-5202', email: 'seongmin625@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-36', index: 36, name: '이예규', roleLevel: '대표', department: '기계공학과', labProfessor: '하지환 교수님', phone: '010-5437-9475', email: '20204012@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-37', index: 37, name: '이철희', roleLevel: '일반', department: '기계공학과', labProfessor: '하지환 교수님', phone: '010-4447-0447', email: '20224015@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-38', index: 38, name: '이민규', roleLevel: '일반', department: '기계공학과', labProfessor: '하지환 교수님', phone: '010-9473-2498', email: '20211394@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-39', index: 39, name: '신우빈', roleLevel: '일반', department: '기계공학과', labProfessor: '하지환 교수님', phone: '010-4772-3721', email: 'ssshinwoovin@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-40', index: 40, name: '정진호', roleLevel: '일반', department: '기계공학과', labProfessor: '하지환 교수님', phone: '010-9568-1713', email: '607jinho@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-41', index: 41, name: '빙성윤', roleLevel: '일반', department: '기계공학과', labProfessor: '하지환 교수님', phone: '010-8572-1565', email: 'smartbing2001@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-42', index: 42, name: '이우진', roleLevel: '일반', department: '기계공학과', labProfessor: '하지환 교수님', phone: '010-4137-4829', email: 'wjin03274@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-43', index: 43, name: '정예림', roleLevel: '일반', department: '신소재공학과', labProfessor: '하지환 교수님', phone: '010-5449-2175', email: 'jungyerim0713@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-44', index: 44, name: '이원섭', roleLevel: '대표', department: '창의융합학과', labProfessor: '정우익 교수님', phone: '010-8741-7849', email: 'hahaman767@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-45', index: 45, name: '김동혁', roleLevel: '일반', department: '창의융합학과', labProfessor: '정우익 교수님', phone: '010-2655-3001', email: 'kdhy3001@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-46', index: 46, name: '이리안', roleLevel: '일반', department: '창의융합학과', labProfessor: '정우익 교수님', phone: '010-6631-6162', email: 'comonlra@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-47', index: 47, name: '임경민', roleLevel: '일반', department: '창의융합학과', labProfessor: '정우익 교수님', phone: '010-8871-9415', email: 'dlariddlas@gmail.com', memo: '', authProvider: 'Manual' },
  { id: 'user-48', index: 48, name: '손민진', roleLevel: '일반', department: '창의융합학과', labProfessor: '정우익 교수님', phone: '010-3072-4154', email: '20232713@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-49', index: 49, name: '구연우', roleLevel: '일반', department: '창의융합학과', labProfessor: '정우익 교수님', phone: '010-8625-3711', email: '20242742@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-50', index: 50, name: '박보미', roleLevel: '일반', department: '창의융합학과', labProfessor: '정우익 교수님', phone: '010-8321-1844', email: '20244099@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-51', index: 51, name: '최진규', roleLevel: '대표', department: '전자공학과', labProfessor: '구치완 교수님', phone: '010-7217-3034', email: '30231153@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-52', index: 52, name: '김정태', roleLevel: '일반', department: '전자공학과', labProfessor: '구치완 교수님', phone: '010-3070-3019', email: 'jeotae@edu.hanbat.ac.kr', memo: '', authProvider: 'Manual' },
  { id: 'user-53', index: 53, name: '구자성', roleLevel: '대표', department: '전자공학과', labProfessor: '백근우 교수님', phone: '010-3103-2501', email: 'koo020716@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-54', index: 54, name: '이동현', roleLevel: '일반', department: '전자공학과', labProfessor: '백근우 교수님', phone: '010-6434-8551', email: 'ddadda05@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-55', index: 55, name: '이유경', roleLevel: '일반', department: '전자공학과', labProfessor: '백근우 교수님', phone: '010-5585-5698', email: 'dbsdb8389@naver.com', memo: '', authProvider: 'Manual' },
  { id: 'user-56', index: 56, name: '최민용', roleLevel: '일반', department: '전자공학과', labProfessor: '백근우 교수님', phone: '010-2315-4255', email: 'cjh103741@naver.com', memo: '', authProvider: 'Manual' }
];

export const initialConsumablesData = [
  { id: 'supply-1', category: '단순소모품', name: '클린 마스크', unit: 'BOX 기준', monthStart: 36, current: 27, minimum: 20, note: 'BOX 기준' },
  { id: 'supply-2', category: '단순소모품', name: '라텍스 장갑 (L)', unit: 'BOX 기준', monthStart: 11, current: 17, minimum: 10, note: 'BOX 기준' },
  { id: 'supply-3', category: '단순소모품', name: '라텍스 장갑 (M)', unit: 'BOX 기준', monthStart: 5, current: 19, minimum: 10, note: 'BOX 기준' },
  { id: 'supply-4', category: '단순소모품', name: '라텍스 장갑 (S)', unit: 'BOX 기준', monthStart: 16, current: 22, minimum: 20, note: 'BOX 기준' },
  { id: 'supply-5', category: '단순소모품', name: 'PVC 장갑 (L)', unit: 'BOX 기준', monthStart: 14, current: 24, minimum: 20, note: 'BOX 기준' },
  { id: 'supply-6', category: '단순소모품', name: 'PVC 장갑 (M)', unit: 'BOX 기준', monthStart: 12, current: 22, minimum: 20, note: 'BOX 기준' },
  { id: 'supply-7', category: '단순소모품', name: 'PVC 장갑 (S)', unit: 'BOX 기준', monthStart: 2, current: 22, minimum: 20, note: 'BOX 기준' },
  { id: 'supply-8', category: '단순소모품', name: '클린룸 sticky mat', unit: '개', monthStart: 37, current: 36, minimum: 20, note: '개' },
  { id: 'supply-9', category: '단순소모품', name: '킴테크 와이퍼', unit: 'BOX 기준', monthStart: 80, current: 75, minimum: 20, note: 'BOX 기준' },
  { id: 'supply-10', category: '단순소모품', name: '알루미늄 호일', unit: '개', monthStart: 69, current: 68, minimum: 20, note: '개' },
  { id: 'supply-11', category: '단순소모품', name: '무진천', unit: '신규주문 필요', monthStart: 0, current: 10, minimum: 10, note: '신규주문 필요' },
  { id: 'supply-12', category: '단순소모품', name: '폐액통', unit: '통', monthStart: 8, current: 21, minimum: 20, note: '2,4주차 수요일 오전' },
  { id: 'supply-13', category: '가스', name: 'N2 gas', unit: '봄베 압력', monthStart: 5.5, current: 12, minimum: 10, note: 'main gas 봄베 regulator 압력 기준' },
  { id: 'supply-14', category: '가스', name: 'O2 gas', unit: '봄베 압력', monthStart: 9.5, current: 9, minimum: 10, note: 'main gas 봄베 regulator 압력 기준' },
  { id: 'supply-15', category: '가스', name: 'Ar gas', unit: '봄베 압력', monthStart: 6, current: 6.5, minimum: 10, note: 'main gas 봄베 regulator 압력 기준' },
  { id: 'supply-16', category: '가스', name: 'CF4 gas', unit: '봄베 압력', monthStart: 8, current: 8, minimum: 10, note: 'main gas 봄베 regulator 압력 기준' },
  { id: 'supply-17', category: '가스', name: 'CHF3 gas', unit: '봄베 압력', monthStart: 4, current: 4, minimum: 5, note: 'main gas 봄베 regulator 압력 기준' },
  { id: 'supply-18', category: 'White room 용액 (산)', name: '황산', unit: '병', monthStart: 2, current: 2, minimum: 5, note: '2병 이하일 때는 분수로 기록' },
  { id: 'supply-19', category: 'White room 용액 (산)', name: '질산', unit: '병', monthStart: 2, current: 2, minimum: 5, note: '2병 이하일 때는 분수로 기록' },
  { id: 'supply-20', category: 'White room 용액 (산)', name: '과산화수소', unit: '병', monthStart: 3, current: 3, minimum: 5, note: '2병 이하일 때는 분수로 기록' },
  { id: 'supply-21', category: 'White room 용액 (산)', name: 'BOE', unit: '병', monthStart: 4, current: 4, minimum: 5, note: '2병 이하일 때는 분수로 기록' },
  { id: 'supply-22', category: 'Yellow room 용액 (유기, 염기)', name: '아세톤', unit: '병', monthStart: 1, current: 4, minimum: 5, note: '2병 이하일 때는 분수로 기록' },
  { id: 'supply-23', category: 'Yellow room 용액 (유기, 염기)', name: 'IPA (이소프로판올)', unit: '병', monthStart: 2, current: 4, minimum: 5, note: '2병 이하일 때는 분수로 기록' },
  { id: 'supply-24', category: 'Yellow room 용액 (유기, 염기)', name: 'AZ300MIF', unit: '병', monthStart: 1, current: 1, minimum: 5, note: '1병 이하일 때는 분수로 기록' },
  { id: 'supply-25', category: 'Yellow room 용액 (유기, 염기)', name: 'AZ GXR601-14cp', unit: '병', monthStart: 1, current: 1, minimum: 5, note: '1병 이하일 때는 분수로 기록' },
  { id: 'supply-26', category: 'Yellow room 용액 (유기, 염기)', name: 'NR9-1000 PY', unit: '병', monthStart: 2, current: 3, minimum: 5, note: '1병 이하일 때는 분수로 기록' },
  { id: 'supply-27', category: 'Yellow room 용액 (유기, 염기)', name: 'RD6', unit: '병', monthStart: 4, current: 4, minimum: 5, note: '1병 이하일 때는 분수로 기록' },
  { id: 'supply-28', category: 'Yellow room 용액 (유기, 염기)', name: 'AZ 5214 E', unit: '병', monthStart: 1, current: 1, minimum: 5, note: '1병 이하일 때는 분수로 기록' },
  { id: 'supply-29', category: 'Yellow room 용액 (유기, 염기)', name: 'AZ AD promoter-K', unit: '병', monthStart: 1, current: 1, minimum: 5, note: '1병 이하일 때는 분수로 기록' },
  { id: 'supply-30', category: '폐기스티커', name: '할로겐폐유기용제', unit: 'EA', monthStart: 33, current: 32, minimum: 20, note: '' },
  { id: 'supply-31', category: '폐기스티커', name: '비할로겐폐유기용제', unit: 'EA', monthStart: 22, current: 50, minimum: 20, note: '' },
  { id: 'supply-32', category: '폐기스티커', name: '폐시약병', unit: 'EA', monthStart: 38, current: 29, minimum: 20, note: '' },
  { id: 'supply-33', category: '폐기스티커', name: '기타폐기물', unit: 'EA', monthStart: 6, current: 50, minimum: 20, note: '' },
  { id: 'supply-34', category: '폐기스티커', name: '폐시약', unit: 'EA', monthStart: 22, current: 22, minimum: 20, note: '' },
  { id: 'supply-35', category: '폐기스티커', name: '폐유독물(액상)', unit: 'EA', monthStart: 14, current: 14, minimum: 10, note: '' },
  { id: 'supply-36', category: '폐기스티커', name: '폐산', unit: 'EA', monthStart: 35, current: 34, minimum: 20, note: '' },
  { id: 'supply-37', category: '폐기스티커', name: '할로겐유기용제', unit: 'EA', monthStart: 28, current: 28, minimum: 20, note: '' },
  { id: 'supply-38', category: '폐기스티커', name: '폐유기용제(고상)', unit: 'EA', monthStart: 14, current: 14, minimum: 10, note: '' },
  { id: 'supply-39', category: '장비 내 소모품', name: 'miniSEM 필라멘트', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '26년 5월 / 여분 4개' },
  { id: 'supply-40', category: '장비 내 소모품', name: 'miniSEM 코팅 물질(PT Target)', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '25년 12월 / 재고 여분 있음' },
  { id: 'supply-41', category: '장비 내 소모품', name: 'ALD TMA 소스', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '24년 5월 / 소스 소진 시 파형 확인' },
  { id: 'supply-42', category: '장비 내 소모품', name: 'ALD TEMAHf 소스', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '24년 5월 / 소스 소진 시 파형 확인' },
  { id: 'supply-43', category: '장비 내 소모품', name: 'MASK aligner UV lamp', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '24년 2월 / UV intensity 확인 필요' },
  { id: 'supply-44', category: '장비 내 소모품', name: '클린부스 헤파필터', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '25년 8월 / 보통 1년 주기 교체' },
  { id: 'supply-45', category: '장비 내 소모품', name: '시약장 필터', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '25년 9월 / 교체 알림이 뜸' },
  { id: 'supply-46', category: '장비 내 소모품', name: '공기정화장치필터', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '25년 11월 / 보통 1년 주기 교체' },
  { id: 'supply-47', category: '장비 내 소모품', name: '초순수제조장치필터', unit: '교체 일자', monthStart: 0, current: 0, minimum: 5, note: '26년 5월 / 4개월 주기 교체' }
];

